version: "3"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ../configs/prometheus/collector.yaml:/etc/otel/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"   # Prometheus scrape endpoint
    depends_on: [prometheus]
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
